vim.g.iconchars = {
  diagnostics = {
    Error = "⛒ ",
    Warn = "⚠ ",
    Info = "Ⓘ ",
    Hint = "Ⓗ ",
  },
  git = {
    LineAdded = "⊕",
    LineModified = "⊙",
    LineRemoved = "⊖",
    FileModified = "⊙",
    FileDeleted = "⊖",
    FileIgnored = "◌",
    FileRenamed = "↻",
    FileStaged = "✓",
    FileUnmerged = "x",
    FileUnstaged = "x",
    FileUntracked = "？",
    Diff = "⤭",
    Repo = "",
    Octoface = "",
    Branch = "⑆",
  },
  kinds = {
    file = "[file]",
    module = "[mod]",
    namespace = "[ns]",
    package = "[pkg]",
    class = "[cls]",
    method = "[meth]",
    property = "[prop]",
    field = "[field]",
    constructor = "[ctor]",
    enum = "[enum]",
    interface = "[iface]",
    ["function"] = "[fn]",
    variable = "[var]",
    constant = "[const]",
    string = "[str]",
    number = "[num]",
    boolean = "[bool]",
    array = "[arr]",
    object = "[obj]",
    key = "[key]",
    null = "[null]",
    enummember = "[member]",
    struct = "[struct]",
    event = "[event]",
    operator = "[op]",
    typeparameter = "[tparam]",
    parameter = "[param]",
    keyword = "[kw]",
  },
  statusline = {
    separators = { left = "█", right = "█" },
    session = "",
    lines = "▤ ",
    label = "☆",
  },
  misc = {
    collapsed = ">",
    expanded = "v",
    condense = "⇞ ",
    h_border = "─",
    v_border = "│ ",
    prompt = "⌕ ",
    next_line = "↩ ",
    textured_box = "▨ ",
    pad_line = "▌",
  },
}

-- Nerdcon Support
vim.g.nerdchars = {
  diagnostics = {
    Error = " ",
    Warn = " ",
    Info = " ",
    Hint = " ",
  },
  git = {
    LineAdded = "",
    LineModified = "",
    LineRemoved = "",
    FileModified = "",
    FileDeleted = "",
    FileIgnored = "◌",
    FileRenamed = "",
    FileStaged = "",
    FileUnmerged = "",
    FileUnstaged = "",
    FileUntracked = "",
    Diff = "",
    Repo = "",
    Octoface = "",
    Branch = "󰘬",
  },
  kinds = {
    module = "󰅩",
    namespace = "󰅩",
    package = "󰅩",
    class = "󰠱",
    interface = "󰠱",
    struct = "󰠱",
    enum = "󰠱",
    method = "󰆧",
    constructor = "󰊕",
    ["function"] = "󰊕",
    property = "󰜢",
    field = "󰜢",
    parameter = "󰏪",
    variable = "󰀫",
    keyword = "󰌋",
    constant = "󰏿",
    enummember = "󰏿",
  },
  misc = {
    collapsed = "󰅂",
    expanded = "󰅀",
    prompt = "  ",
    textured_box = "󰿦 ",
  },
  statusline = {
    separators = { left = "", right = "" },
    session = " ",
    lines = "󱪶 ",
    label = "󰃃",
  },
}

if vim.g.use_nerdfonts then
  vim.g.iconchars = vim.tbl_deep_extend("force", vim.g.iconchars, vim.g.nerdchars)
end
